spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ledger?serverTimezone=GMT%2B8
    username: root
    password: '@root123'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone:
            'UTC'
